### ISSUE TITLE
Request feature 

### ISSUE THREAD

**Issue by knkrth** [abhinavsuthar/Android_Spy_App#1]
Hi, Is there is a way to add this https://github.com/OddCN/screen-share-to-browser on this project? Where user can view the live activity of the screen on the website.

**Comment by abhinavsuthar** [comment]
I don't know about it till now. But you can try webrtc. And there is a open source app named signal, which is an open source version of WhatsApp. So you can learn video streaming. App is available on play store as well as on GitHub. Source code: https://github.com/WhisperSystems/Signal-Android

**Comment by knkrth** [comment]
Ok, I'll look into it. Thanks.

**Comment by lordcharlx** [comment]
the server side is not as same as the one you hosted on https://hawkshaw.tk/ its rather a copy of 
https://github.com/adonespitogo/AdoBot

**Comment by knkrth** [comment]
@abhinavsuthar Are u planning to release android spy app(v2.0)?

**Comment by abhinavsuthar** [comment]
@knkrth Yupp!, I am working on Hawkshaw Spy App, which is android spy app(v2.0). But, I'll not share the source code of Hawkshaw Android Spy App. Instead, I'll write a blog on Hawkshaw demonstrating some functionalities. FYI, Hawkshaw is using firebase for sending the command to BOT, database, and some other stuff.

**Comment by abhinavsuthar** [comment]
@lordcharlx Hawkshaw and this project are completely different. Hawkshaw is Android Spy App v2.0. For this project, I referred to [Adobot](https://github.com/adonespitogo/AdoBot).

**Comment by lordcharlx** [comment]
How do i contact you! I want us to have a deal !

**Comment by dark4ng3l** [comment]
haha , bro i guess there are alots more want to deal with u :P push it for those u dun want to involve with :P
