### ISSUE TITLE
Regarding app

### ISSUE THREAD

**Issue by swagkarna** [abhinavsuthar/Android_Spy_App#17]
Hi . Android Devices after android 8.0 update they are using aggressive battery saving algorithm to extend their battery life. Due to that app will stop running in background when the screen is locked and it will stop the app permanently running from background whether your app can bypass this and it is 100% persistent?

**Comment by saksham2410** [comment]
Please check the website and try out the app. We are actually asking permission for disabling battery optimisation for the app.
