### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lordcharlx** [abhinavsuthar/Android_Spy_App#3]
the server side is not as same as the one you hosted on https://hawkshaw.tk/ its rather a copy of 
https://github.com/adonespitogo/AdoBot

**Comment by abhinavsuthar** [comment]
FYI, Hawkshaw is a different project and I do not wanna share the source code of Hawkshaw.
Hint: Use **firebase cloud messaging** for sending the command to BOT and send data back to your server depending on the command given.

**Comment by lordcharlx** [comment]
@abhinavsuthar please can you pm me for private discussion via Whatsapp 
 +17653515190

**Comment by shakib-h** [comment]
Can you please mail me the source code of Hawkshaw at [hawkshaw@ajshakib.xyz](mailto:hawkshaw@ajshakib.xyz) ?
